version: '3'
services:
    nginx:
        ports:
            - '3333:80'
    node-app:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_USER=root
            - MONGO_PASSWORD=tal1962
            - REDIS_SECRET=teboul
        command: npm run dev
        depends_on:
            - mongo
    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=tal1962
