version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    node-app:
        build: .

        environment:
            - PORT=3333
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=tal1962
        volumes:
            - mongo-db:/data/db
    redis:
        image: redis:6.0

volumes:
    mongo-db:
